# Dynamic Process Alarm Prioritization {#Alarm-Dam}

#### Keywords {-}

Alarm Management, Alarm Systems, Machine Learning, Human Machine Interface, Continuous Manufacturing

## Alarm Flood

Operators in a manufacturing plant are confronted with a steady stream of alarms which are meant to alert them to adverse conditions.  It is up to the operators to use their experience to determine which issues to tackle first.  Sometimes they miss an important alarm which results in downtime and an economic loss from lost production.  It is common that an alarm interface will consist of a large table that dynamically fills with the most recent alarm information.  During times when a process is upset, this table can be continuously updating which can be overwhelming even for experienced operators.

By leveraging the thousands of measurements that are already aggregated in an automated control system it's possible to alleviate some of the pressure.  Currently, the process of alarm management is often implemented using a labor intensive brute force technique involving a large time investment from a multidisciplinary team.[@hollifield_understanding_2010]  By generating a model which determines what alarms are critical during the current mode of operation, the operators will benefit from their collective experience without the large team performing alarm management analysis.  The model will act as a tool, which used in conjunction with human insight, will help reduce lost production by improving the meaningful productivity of operators.

## Dynamic Prioritization of Alarms

The solution is to train an algorithm with information about how long it takes to correct a problem signaled by and alarm and the potential consequence of ignoring it.  This algorithm will be used to dynamically assess the priorities and present the operator with the most pertinent information. The priority of an alarm increases with the consequence of the failing to take action, and the amount of time to take that action.  So, issues resulting in damage to expensive equipment that occur quickly would be used to assign the highest priority.  This is possible by reconciling the logs of all the operator actions related to a piece of equipment which occurred between the generation of the equipment alarm and its resolution.  The alarms and actions will both be categorized by the associated equipment.

The end result will be a graphical interface that shows an operator only the 5-10 most important issues that they need to correct ranked by importance.  It will also offer options for the operator to override the predicted importance to provide live feedback.  Rather than a large table of alarms the interface will allow for quick navigation to top 5-10 issues while also providing some summary bar graphs to illustrate whether the issues are isolated to a single area, or plantwide[@tufte_visual_nodate].  The interface will adapt to the current user to compensate for their lack of experience.  To shorten the onboarding process, a common low experience account would serve as a baseline before it customized to a new employee.  

One demonstrative example would be a high temperature alarm on a product storage tank.  Perhaps a single high temperature alarm may not represent a major threat to the product's quality.  However, if several of the high temperature alarms begin to activate then the model will recognize the important systemic issue with the cooling system and prioritize the group of alarms.

There are groups of alarms clogging up the logs that do not provide the operators actionable information.  Some of these alarms may just need to be routed to different personnel, perhaps maintenance, or management.  Others may not have any value at all and can be discarded.  By routing these alarms to the proper parties, it will improve the process for all stakeholders.

## Evolution of the Operator Role

There will be several hurdles to developing the model.  There are many biases in the data set, for example, some operators are more experienced than others, and already know which alarms require immediate attention.  Experienced operators will take action proactively, in some cases even before an alarm is triggered.  One possible solution would be to identify when an operator alters the conditions of some equipment in the absence of alarms.  This may require manual intervention to determine what adverse conditions were avoided.

With the implementation of a Dynamic Process Alarm Prioritization model, operators will divert their attention to the most important tasks.  The increase in their meaningful productivity will reduce the likelihood of damaging equipment or halting production because an operator missed a critical alarm.  Because they are no longer forced to concentrate on the constant alarm stream they will have time to think proactively resulting in fewer alarms overall.  By embedding the experience of all the operators in the model, an estimated week of unplanned downtime could be avoided annually increasing throughput by millions of dollars.
